### PR TITLE
Updating the branch 1.0.8

### PR DESCRIPTION
**Pull request by aranaravi**
The request raised to merge the changes has been done against the master UI and the CRUD operation has been implemented in the Master Data screens.

### CODE REVIEW

**Comment by srinivasanMT** [comment]
@Ajay1596  please review

**Comment by Ajay1596** [comment]
Can I know are the changes that's been done. Because I see changes in 80 files.

**Comment by aranaravi** [comment]
Hi Ajay,

All the Master Data related to CRUD operation, Devices and Machines Add and
Update method has been developed.

Thanks & Regards,
Aravindh.

**Comment by Ajay1596** [comment]
Hi Aravindh,

Can you fix the unused imports issue reported by lgtm.

**Comment by Ajay1596** [comment]
Hi Aravindh,

As discussed make the changes in the below files .
  1.admin-ui/src/app/core/services/authguard.service.ts 
  2.admin-ui/src/app/app.constants.ts
  3.admin-ui/src/app/app.utils.ts (Utils -->Utilss)
  4.admin-ui/src/app/core/services/header.service.ts (roles --> hardcoded)
  5.admin-ui/src/assets/config.json (base url --> has to be changed back to dev)

**Pull request merged**
